name: 🚀 Update Live Channels and Deploy Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force commit even if no changes'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: update-and-deploy
      cancel-in-progress: false

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm ci --no-audit --prefer-offline

      - name: 🔑 Verify YouTube API Key (for update step)
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          if [ -z "$YOUTUBE_API_KEY" ]; then
            echo "❌ ERROR: YOUTUBE_API_KEY secret not configured!"
            exit 1
          else
            echo "✅ YouTube API key detected (${#YOUTUBE_API_KEY} chars)"
          fi

      - name: 🎬 Update live channels data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          node scripts/update_popular_live.js

      - name: 📊 Check for changes
        id: changes
        run: |
          if git diff --quiet public/popular_live.json; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git status --porcelain
          fi

      - name: 🏷️ Commit updated data
        if: steps.changes.outputs.has_changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/popular_live.json
          git commit -m "🎬 Update live channels and deploy"
          git push

      - name: 🛠️ Build site
        run: |
          npm run build

      - name: 📦 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          force_orphan: true
